version: '2'
services:
    app:
        image: php:7
        command: php -S 0.0.0.0:8000 /app/index.php
        ports:
        - 8000:8000
        volumes:
        - ../:/app
    mockServer:
        image: node:slim
        command: sh -c "cd /app; exec npm run mock:server"
        ports:
        - 9000:9000
        volumes:
        - ../:/app